[target.x86_64-unknown-linux-gnu]
image = "vector-cross-env:x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "vector-cross-env:aarch64-unknown-linux-gnu"

[target.x86_64-unknown-linux-musl]
image = "vector-cross-env:x86_64-unknown-linux-musl"

[target.aarch64-unknown-linux-musl]
image = "vector-cross-env:aarch64-unknown-linux-musl"

[build.env]
passthrough = [
    "RUST_BACKTRACE",
    "RUST_LOG",
    "TRAVIS",
    "PKG_CONFIG_ALL_STATIC",
    "LIBZ_SYS_STATIC",
    "OPENSSL_STATIC",
    "SASL2_STATIC",
]
